package nl.mpcjanssen.simpletask.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import nl.mpcjanssen.simpletask.dao.TodoEntry;
import nl.mpcjanssen.simpletask.dao.TodoTags;
import nl.mpcjanssen.simpletask.dao.TodoLists;
import nl.mpcjanssen.simpletask.dao.TodoStatus;

import nl.mpcjanssen.simpletask.dao.TodoEntryDao;
import nl.mpcjanssen.simpletask.dao.TodoTagsDao;
import nl.mpcjanssen.simpletask.dao.TodoListsDao;
import nl.mpcjanssen.simpletask.dao.TodoStatusDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todoEntryDaoConfig;
    private final DaoConfig todoTagsDaoConfig;
    private final DaoConfig todoListsDaoConfig;
    private final DaoConfig todoStatusDaoConfig;

    private final TodoEntryDao todoEntryDao;
    private final TodoTagsDao todoTagsDao;
    private final TodoListsDao todoListsDao;
    private final TodoStatusDao todoStatusDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todoEntryDaoConfig = daoConfigMap.get(TodoEntryDao.class).clone();
        todoEntryDaoConfig.initIdentityScope(type);

        todoTagsDaoConfig = daoConfigMap.get(TodoTagsDao.class).clone();
        todoTagsDaoConfig.initIdentityScope(type);

        todoListsDaoConfig = daoConfigMap.get(TodoListsDao.class).clone();
        todoListsDaoConfig.initIdentityScope(type);

        todoStatusDaoConfig = daoConfigMap.get(TodoStatusDao.class).clone();
        todoStatusDaoConfig.initIdentityScope(type);

        todoEntryDao = new TodoEntryDao(todoEntryDaoConfig, this);
        todoTagsDao = new TodoTagsDao(todoTagsDaoConfig, this);
        todoListsDao = new TodoListsDao(todoListsDaoConfig, this);
        todoStatusDao = new TodoStatusDao(todoStatusDaoConfig, this);

        registerDao(TodoEntry.class, todoEntryDao);
        registerDao(TodoTags.class, todoTagsDao);
        registerDao(TodoLists.class, todoListsDao);
        registerDao(TodoStatus.class, todoStatusDao);
    }
    
    public void clear() {
        todoEntryDaoConfig.getIdentityScope().clear();
        todoTagsDaoConfig.getIdentityScope().clear();
        todoListsDaoConfig.getIdentityScope().clear();
        todoStatusDaoConfig.getIdentityScope().clear();
    }

    public TodoEntryDao getTodoEntryDao() {
        return todoEntryDao;
    }

    public TodoTagsDao getTodoTagsDao() {
        return todoTagsDao;
    }

    public TodoListsDao getTodoListsDao() {
        return todoListsDao;
    }

    public TodoStatusDao getTodoStatusDao() {
        return todoStatusDao;
    }

}
