package nl.mpcjanssen.simpletask.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import nl.mpcjanssen.simpletask.dao.Entry;
import nl.mpcjanssen.simpletask.dao.VisibleLine;

import nl.mpcjanssen.simpletask.dao.EntryDao;
import nl.mpcjanssen.simpletask.dao.VisibleLineDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig entryDaoConfig;
    private final DaoConfig visibleLineDaoConfig;

    private final EntryDao entryDao;
    private final VisibleLineDao visibleLineDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        entryDaoConfig = daoConfigMap.get(EntryDao.class).clone();
        entryDaoConfig.initIdentityScope(type);

        visibleLineDaoConfig = daoConfigMap.get(VisibleLineDao.class).clone();
        visibleLineDaoConfig.initIdentityScope(type);

        entryDao = new EntryDao(entryDaoConfig, this);
        visibleLineDao = new VisibleLineDao(visibleLineDaoConfig, this);

        registerDao(Entry.class, entryDao);
        registerDao(VisibleLine.class, visibleLineDao);
    }
    
    public void clear() {
        entryDaoConfig.getIdentityScope().clear();
        visibleLineDaoConfig.getIdentityScope().clear();
    }

    public EntryDao getEntryDao() {
        return entryDao;
    }

    public VisibleLineDao getVisibleLineDao() {
        return visibleLineDao;
    }

}
