package nl.mpcjanssen.simpletask.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ENTRY_TAG".
 */
public class EntryTag {

    private long entryLine;
    /** Not-null value. */
    private String text;

    public EntryTag() {
    }

    public EntryTag(long entryLine, String text) {
        this.entryLine = entryLine;
        this.text = text;
    }

    public long getEntryLine() {
        return entryLine;
    }

    public void setEntryLine(long entryLine) {
        this.entryLine = entryLine;
    }

    /** Not-null value. */
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(String text) {
        this.text = text;
    }

}
