package nl.mpcjanssen.simpletask.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import nl.mpcjanssen.simpletask.dao.EntryList;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ENTRY_LIST".
*/
public class EntryListDao extends AbstractDao<EntryList, Void> {

    public static final String TABLENAME = "ENTRY_LIST";

    /**
     * Properties of entity EntryList.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property EntryLine = new Property(0, long.class, "entryLine", false, "ENTRY_LINE");
        public final static Property Text = new Property(1, String.class, "text", false, "TEXT");
    };

    private Query<EntryList> entry_EntryListListQuery;

    public EntryListDao(DaoConfig config) {
        super(config);
    }
    
    public EntryListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ENTRY_LIST\" (" + //
                "\"ENTRY_LINE\" INTEGER NOT NULL ," + // 0: entryLine
                "\"TEXT\" TEXT NOT NULL );"); // 1: text
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ENTRY_LIST\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, EntryList entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getEntryLine());
        stmt.bindString(2, entity.getText());
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public EntryList readEntity(Cursor cursor, int offset) {
        EntryList entity = new EntryList( //
            cursor.getLong(offset + 0), // entryLine
            cursor.getString(offset + 1) // text
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, EntryList entity, int offset) {
        entity.setEntryLine(cursor.getLong(offset + 0));
        entity.setText(cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(EntryList entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(EntryList entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "entryListList" to-many relationship of Entry. */
    public List<EntryList> _queryEntry_EntryListList(long entryLine) {
        synchronized (this) {
            if (entry_EntryListListQuery == null) {
                QueryBuilder<EntryList> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.EntryLine.eq(null));
                entry_EntryListListQuery = queryBuilder.build();
            }
        }
        Query<EntryList> query = entry_EntryListListQuery.forCurrentThread();
        query.setParameter(0, entryLine);
        return query.list();
    }

}
