package nl.mpcjanssen.simpletask.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ENTRY".
 */
public class Entry {

    private long line;
    private boolean selected;
    private boolean hidden;
    /** Not-null value. */
    private String text;
    private boolean completed;
    /** Not-null value. */
    private String priority;
    private String completionDate;
    private String createDate;
    private String thresholdDate;
    private String dueDate;
    private int endOfCompPrefix;
    private Lists lists;
    private Tags tags;

    public Entry() {
    }

    public Entry(long line) {
        this.line = line;
    }

    public Entry(long line, boolean selected, boolean hidden, String text, boolean completed, String priority, String completionDate, String createDate, String thresholdDate, String dueDate, int endOfCompPrefix, Lists lists, Tags tags) {
        this.line = line;
        this.selected = selected;
        this.hidden = hidden;
        this.text = text;
        this.completed = completed;
        this.priority = priority;
        this.completionDate = completionDate;
        this.createDate = createDate;
        this.thresholdDate = thresholdDate;
        this.dueDate = dueDate;
        this.endOfCompPrefix = endOfCompPrefix;
        this.lists = lists;
        this.tags = tags;
    }

    public long getLine() {
        return line;
    }

    public void setLine(long line) {
        this.line = line;
    }

    public boolean getSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

    public boolean getHidden() {
        return hidden;
    }

    public void setHidden(boolean hidden) {
        this.hidden = hidden;
    }

    /** Not-null value. */
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(String text) {
        this.text = text;
    }

    public boolean getCompleted() {
        return completed;
    }

    public void setCompleted(boolean completed) {
        this.completed = completed;
    }

    /** Not-null value. */
    public String getPriority() {
        return priority;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getCompletionDate() {
        return completionDate;
    }

    public void setCompletionDate(String completionDate) {
        this.completionDate = completionDate;
    }

    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    public String getThresholdDate() {
        return thresholdDate;
    }

    public void setThresholdDate(String thresholdDate) {
        this.thresholdDate = thresholdDate;
    }

    public String getDueDate() {
        return dueDate;
    }

    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }

    public int getEndOfCompPrefix() {
        return endOfCompPrefix;
    }

    public void setEndOfCompPrefix(int endOfCompPrefix) {
        this.endOfCompPrefix = endOfCompPrefix;
    }

    public Lists getLists() {
        return lists;
    }

    public void setLists(Lists lists) {
        this.lists = lists;
    }

    public Tags getTags() {
        return tags;
    }

    public void setTags(Tags tags) {
        this.tags = tags;
    }

}
