package nl.mpcjanssen.simpletask.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import nl.mpcjanssen.simpletask.dao.TodoEntry;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TODO_ENTRY".
*/
public class TodoEntryDao extends AbstractDao<TodoEntry, Long> {

    public static final String TABLENAME = "TODO_ENTRY";

    /**
     * Properties of entity TodoEntry.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Line = new Property(0, long.class, "line", true, "LINE");
        public final static Property Text = new Property(1, String.class, "text", false, "TEXT");
    };


    public TodoEntryDao(DaoConfig config) {
        super(config);
    }
    
    public TodoEntryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TODO_ENTRY\" (" + //
                "\"LINE\" INTEGER PRIMARY KEY NOT NULL ," + // 0: line
                "\"TEXT\" TEXT NOT NULL );"); // 1: text
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TODO_ENTRY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TodoEntry entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getLine());
        stmt.bindString(2, entity.getText());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TodoEntry readEntity(Cursor cursor, int offset) {
        TodoEntry entity = new TodoEntry( //
            cursor.getLong(offset + 0), // line
            cursor.getString(offset + 1) // text
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TodoEntry entity, int offset) {
        entity.setLine(cursor.getLong(offset + 0));
        entity.setText(cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TodoEntry entity, long rowId) {
        entity.setLine(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TodoEntry entity) {
        if(entity != null) {
            return entity.getLine();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
