package nl.mpcjanssen.simpletask.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TODO_ENTRY".
 */
public class TodoEntry {

    private long line;
    /** Not-null value. */
    private String text;

    public TodoEntry() {
    }

    public TodoEntry(long line) {
        this.line = line;
    }

    public TodoEntry(long line, String text) {
        this.line = line;
        this.text = text;
    }

    public long getLine() {
        return line;
    }

    public void setLine(long line) {
        this.line = line;
    }

    /** Not-null value. */
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(String text) {
        this.text = text;
    }

}
