package nl.mpcjanssen.simpletask.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TODO_LISTS".
 */
public class TodoLists {

    /** Not-null value. */
    private String list;

    public TodoLists() {
    }

    public TodoLists(String list) {
        this.list = list;
    }

    /** Not-null value. */
    public String getList() {
        return list;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setList(String list) {
        this.list = list;
    }

}
