package nl.mpcjanssen.simpletask.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import nl.mpcjanssen.simpletask.dao.VisibleLine;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VISIBLE_LINE".
*/
public class VisibleLineDao extends AbstractDao<VisibleLine, Long> {

    public static final String TABLENAME = "VISIBLE_LINE";

    /**
     * Properties of entity VisibleLine.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Position = new Property(0, long.class, "position", true, "POSITION");
        public final static Property IsHeader = new Property(1, boolean.class, "isHeader", false, "IS_HEADER");
        public final static Property TaskLine = new Property(2, Long.class, "taskLine", false, "TASK_LINE");
        public final static Property Header = new Property(3, String.class, "header", false, "HEADER");
        public final static Property Count = new Property(4, Long.class, "count", false, "COUNT");
    };

    private DaoSession daoSession;


    public VisibleLineDao(DaoConfig config) {
        super(config);
    }
    
    public VisibleLineDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VISIBLE_LINE\" (" + //
                "\"POSITION\" INTEGER PRIMARY KEY NOT NULL ," + // 0: position
                "\"IS_HEADER\" INTEGER NOT NULL ," + // 1: isHeader
                "\"TASK_LINE\" INTEGER," + // 2: taskLine
                "\"HEADER\" TEXT," + // 3: header
                "\"COUNT\" INTEGER);"); // 4: count
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VISIBLE_LINE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, VisibleLine entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getPosition());
        stmt.bindLong(2, entity.getIsHeader() ? 1L: 0L);
 
        Long taskLine = entity.getTaskLine();
        if (taskLine != null) {
            stmt.bindLong(3, taskLine);
        }
 
        String header = entity.getHeader();
        if (header != null) {
            stmt.bindString(4, header);
        }
 
        Long count = entity.getCount();
        if (count != null) {
            stmt.bindLong(5, count);
        }
    }

    @Override
    protected void attachEntity(VisibleLine entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public VisibleLine readEntity(Cursor cursor, int offset) {
        VisibleLine entity = new VisibleLine( //
            cursor.getLong(offset + 0), // position
            cursor.getShort(offset + 1) != 0, // isHeader
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // taskLine
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // header
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // count
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, VisibleLine entity, int offset) {
        entity.setPosition(cursor.getLong(offset + 0));
        entity.setIsHeader(cursor.getShort(offset + 1) != 0);
        entity.setTaskLine(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setHeader(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCount(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(VisibleLine entity, long rowId) {
        entity.setPosition(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(VisibleLine entity) {
        if(entity != null) {
            return entity.getPosition();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getEntryDao().getAllColumns());
            builder.append(" FROM VISIBLE_LINE T");
            builder.append(" LEFT JOIN ENTRY T0 ON T.\"TASK_LINE\"=T0.\"LINE\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected VisibleLine loadCurrentDeep(Cursor cursor, boolean lock) {
        VisibleLine entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Entry entry = loadCurrentOther(daoSession.getEntryDao(), cursor, offset);
        entity.setEntry(entry);

        return entity;    
    }

    public VisibleLine loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<VisibleLine> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<VisibleLine> list = new ArrayList<VisibleLine>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<VisibleLine> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<VisibleLine> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
